GET http://localhost:5248/products

###
GET http://localhost:5248/products/2

###
POST http://localhost:5248/products
Content-Type: application/json

{
    "name": "Nike Air Force 1",
    "categoryId": 3,
    "price": 1499.99,
    "release": "2017-08-22"
}

###
PUT http://localhost:5248/products/10
Content-Type: application/json

{
    "name": "Blonde.",
    "categoryId": "Rhythm and Blues",
    "price": 499.49,
    "release": "2017-08-22"
}

###
DELETE http://localhost:5248/products/1
Content-Type: application/json